import { defineCommand } from 'citty'
import { resolve } from 'node:path'
import { existsSync, readFileSync, writeFileSync, renameSync } from 'node:fs'
import type { SecretStatus, SecretsAuditResult } from '../types.js'
import { CLI_ERROR_CODES } from '../types.js'
import { resolveRoot, success, failure, outputResult } from '../utils.js'
import type { SecretsSchema, SecretDefinition, Stage } from '@ripple-next/config'
import { defineSecrets, getRequiredForStage } from '@ripple-next/config'

const VALID_STAGES: Stage[] = ['dev', 'staging', 'production', 'test']

/**
 * Try to load the platform secrets schema from known locations.
 *
 * Loads from `docs/secrets.schema.json` (generated by build or CI).
 * TypeScript source parsing is not supported at CLI runtime — use
 * `pnpm build` to generate the JSON schema from the TS source.
 */
function loadSchema(root: string): SecretsSchema | undefined {
  const jsonPath = resolve(root, 'docs/secrets.schema.json')
  if (!existsSync(jsonPath)) {
    return undefined
  }

  try {
    const raw = readFileSync(jsonPath, 'utf-8')
    const parsed = JSON.parse(raw) as Record<string, unknown>

    // Validate it looks like a secrets schema (has at least one entry with required fields)
    const entries = Object.entries(parsed)
    if (entries.length === 0) {
      return undefined
    }

    return defineSecrets(parsed as Record<string, SecretDefinition>)
  } catch {
    return undefined
  }
}

/**
 * Check whether a secret is set in the environment.
 */
function isSecretSet(name: string): boolean {
  return process.env[name] !== undefined && process.env[name] !== ''
}

/**
 * Mask a secret value for display.
 */
function maskValue(value: string): string {
  if (value.length <= 4) return '****'
  return value.slice(0, 2) + '****' + value.slice(-2)
}

/**
 * Validate stage argument and return a typed Stage or undefined.
 */
function parseStage(stage: string | undefined): Stage | undefined {
  if (!stage) return undefined
  if (VALID_STAGES.includes(stage as Stage)) {
    return stage as Stage
  }
  return undefined
}

/**
 * Build SecretStatus entries from a schema, optionally filtered by stage.
 */
function buildSecretStatuses(
  schema: SecretsSchema,
  stage?: Stage
): SecretStatus[] {
  return Object.entries(schema)
    .filter(([, def]) => !stage || def.stages.includes(stage))
    .map(([name, def]) => ({
      name,
      required: def.required,
      stages: def.stages,
      format: def.format,
      group: def.group,
      kind: def.kind,
      status: isSecretSet(name) ? ('set' as const) : ('missing' as const),
    }))
}

// ── Subcommands ──────────────────────────────────────────────────────

const listCommand = defineCommand({
  meta: {
    name: 'list',
    description: 'List secrets from the schema, optionally filtered by stage',
  },
  args: {
    stage: {
      type: 'string',
      description: 'Filter by deployment stage (dev, staging, production, test)',
    },
    json: {
      type: 'boolean',
      description: 'Output as JSON CommandResult',
      default: false,
    },
    verbose: {
      type: 'boolean',
      description: 'Show detailed output',
      default: false,
    },
  },
  run({ args }) {
    const startTime = Date.now()
    const root = resolveRoot()
    const schema = loadSchema(root)

    if (!schema) {
      const result = failure(
        'secrets list',
        CLI_ERROR_CODES.SECRETS_NOT_FOUND,
        'Could not load secrets schema. No schema file found.',
        startTime,
        'Ensure packages/config/src/secrets.schema.ts exists or docs/secrets.schema.json is generated.'
      )
      outputResult(result, args)
      process.exitCode = 1
      return
    }

    const stage = parseStage(args.stage)
    if (args.stage && !stage) {
      const result = failure(
        'secrets list',
        CLI_ERROR_CODES.MISSING_ARGUMENT,
        `Invalid stage "${args.stage}". Valid stages: ${VALID_STAGES.join(', ')}`,
        startTime
      )
      outputResult(result, args)
      process.exitCode = 1
      return
    }

    const secrets = buildSecretStatuses(schema, stage)
    const result = success(
      'secrets list',
      {
        stage: stage ?? 'all',
        total: secrets.length,
        secrets,
      },
      startTime
    )

    outputResult(result, args)

    if (!args.json) {
      for (const s of secrets) {
        const icon = s.status === 'set' ? 'SET' : 'MISSING'
        process.stdout.write(`  [${icon}] ${s.name} (${s.format}) — ${s.required ? 'required' : 'optional'}\n`)
      }
    }
  },
})

const requiredCommand = defineCommand({
  meta: {
    name: 'required',
    description: 'List required secrets for a stage with set/missing status',
  },
  args: {
    stage: {
      type: 'string',
      description: 'Deployment stage (dev, staging, production, test)',
      required: true,
    },
    json: {
      type: 'boolean',
      description: 'Output as JSON CommandResult',
      default: false,
    },
    verbose: {
      type: 'boolean',
      description: 'Show detailed output',
      default: false,
    },
  },
  run({ args }) {
    const startTime = Date.now()
    const root = resolveRoot()
    const schema = loadSchema(root)

    if (!schema) {
      const result = failure(
        'secrets required',
        CLI_ERROR_CODES.SECRETS_NOT_FOUND,
        'Could not load secrets schema.',
        startTime,
        'Ensure the secrets schema exists.'
      )
      outputResult(result, args)
      process.exitCode = 1
      return
    }

    const stage = parseStage(args.stage)
    if (!stage) {
      const result = failure(
        'secrets required',
        CLI_ERROR_CODES.MISSING_ARGUMENT,
        `Invalid stage "${args.stage}". Valid stages: ${VALID_STAGES.join(', ')}`,
        startTime
      )
      outputResult(result, args)
      process.exitCode = 1
      return
    }

    const requiredNames = getRequiredForStage(schema, stage)
    const secrets: SecretStatus[] = requiredNames.map((name) => {
      const def = schema[name]
      return {
        name,
        required: true,
        stages: def.stages,
        format: def.format,
        group: def.group,
        kind: def.kind,
        status: isSecretSet(name) ? ('set' as const) : ('missing' as const),
      }
    })

    const setCount = secrets.filter((s) => s.status === 'set').length
    const missingCount = secrets.filter((s) => s.status === 'missing').length

    const result = success(
      'secrets required',
      {
        stage,
        total: secrets.length,
        set: setCount,
        missing: missingCount,
        secrets,
      },
      startTime
    )

    outputResult(result, args)

    if (!args.json) {
      for (const s of secrets) {
        const icon = s.status === 'set' ? 'SET' : 'MISSING'
        process.stdout.write(`  [${icon}] ${s.name} (${s.format})\n`)
      }
      if (missingCount > 0) {
        process.stdout.write(`\n  ${missingCount} required secret(s) missing for stage "${stage}".\n`)
      }
    }
  },
})

const getCommand = defineCommand({
  meta: {
    name: 'get',
    description: 'Get a single secret metadata and check if set',
  },
  args: {
    name: {
      type: 'positional',
      description: 'Secret name',
      required: true,
    },
    stage: {
      type: 'string',
      description: 'Deployment stage for context',
    },
    json: {
      type: 'boolean',
      description: 'Output as JSON CommandResult',
      default: false,
    },
    verbose: {
      type: 'boolean',
      description: 'Show detailed output',
      default: false,
    },
  },
  run({ args }) {
    const startTime = Date.now()
    const root = resolveRoot()
    const schema = loadSchema(root)

    if (!schema) {
      const result = failure(
        'secrets get',
        CLI_ERROR_CODES.SECRETS_NOT_FOUND,
        'Could not load secrets schema.',
        startTime,
        'Ensure the secrets schema exists.'
      )
      outputResult(result, args)
      process.exitCode = 1
      return
    }

    const secretName = args.name as string
    const def = schema[secretName]

    if (!def) {
      const result = failure(
        'secrets get',
        CLI_ERROR_CODES.SECRETS_NOT_FOUND,
        `Secret "${secretName}" not found in schema.`,
        startTime,
        `Available secrets: ${Object.keys(schema).join(', ')}`
      )
      outputResult(result, args)
      process.exitCode = 1
      return
    }

    const envValue = process.env[secretName]
    const isSet = envValue !== undefined && envValue !== ''

    const data: {
      name: string
      description: string
      required: boolean
      stages: string[]
      format: string
      group?: string
      kind?: string
      status: 'set' | 'missing'
      maskedValue?: string
    } = {
      name: secretName,
      description: def.description,
      required: def.required,
      stages: def.stages,
      format: def.format,
      group: def.group,
      kind: def.kind,
      status: isSet ? 'set' : 'missing',
    }

    // Only show masked value in non-JSON mode or when verbose
    if (isSet && envValue) {
      data.maskedValue = maskValue(envValue)
    }

    const result = success('secrets get', data, startTime)
    outputResult(result, args)

    if (!args.json) {
      process.stdout.write(`  ${secretName}: ${data.status}\n`)
      process.stdout.write(`    Description: ${def.description}\n`)
      process.stdout.write(`    Required: ${def.required}\n`)
      process.stdout.write(`    Format: ${def.format}\n`)
      process.stdout.write(`    Stages: ${def.stages.join(', ')}\n`)
      if (data.maskedValue) {
        process.stdout.write(`    Value: ${data.maskedValue}\n`)
      }
    }
  },
})

const setCommand = defineCommand({
  meta: {
    name: 'set',
    description: 'Set a secret value (local dev: writes to .env; other stages: shows instructions)',
  },
  args: {
    name: {
      type: 'positional',
      description: 'Secret name',
      required: true,
    },
    stage: {
      type: 'string',
      description: 'Deployment stage',
      default: 'dev',
    },
    value: {
      type: 'string',
      description: 'Secret value to set',
      required: true,
    },
    json: {
      type: 'boolean',
      description: 'Output as JSON CommandResult',
      default: false,
    },
    verbose: {
      type: 'boolean',
      description: 'Show detailed output',
      default: false,
    },
  },
  run({ args }) {
    const startTime = Date.now()
    const root = resolveRoot()

    const secretName = args.name as string
    const secretValue = args.value

    const stage = parseStage(args.stage)
    if (!stage) {
      const result = failure(
        'secrets set',
        CLI_ERROR_CODES.MISSING_ARGUMENT,
        `Invalid stage "${args.stage}". Valid stages: ${VALID_STAGES.join(', ')}`,
        startTime
      )
      outputResult(result, args)
      process.exitCode = 1
      return
    }

    if (stage === 'dev' || stage === 'test') {
      // Write to local .env file atomically using a temp file
      const envFile = stage === 'dev' ? '.env' : `.env.${stage}`
      const envPath = resolve(root, envFile)
      const tmpPath = `${envPath}.tmp.${process.pid}`

      let content = ''
      try {
        content = readFileSync(envPath, 'utf-8')
      } catch {
        // File doesn't exist yet — start with empty content
      }

      // Check if the key already exists and replace it, or append
      const escaped = secretName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
      const regex = new RegExp(`^${escaped}=.*$`, 'm')
      if (regex.test(content)) {
        content = content.replace(regex, `${secretName}=${secretValue}`)
      } else {
        const newline = content.endsWith('\n') || content === '' ? '' : '\n'
        content += `${newline}${secretName}=${secretValue}\n`
      }

      // Write to temp file then rename for atomicity (avoids TOCTOU race)
      writeFileSync(tmpPath, content, 'utf-8')
      renameSync(tmpPath, envPath)

      const result = success(
        'secrets set',
        {
          name: secretName,
          stage,
          target: envFile,
          action: 'written',
        },
        startTime
      )
      outputResult(result, args)

      if (!args.json) {
        process.stdout.write(`  Set ${secretName} in ${envFile}\n`)
      }
    } else {
      // For staging/production, output instructions
      const result = success(
        'secrets set',
        {
          name: secretName,
          stage,
          action: 'instructions',
          instructions: [
            `For stage "${stage}", secrets should be managed via SSM Parameter Store or Secrets Manager.`,
            `Run: aws ssm put-parameter --name "/${stage}/${secretName}" --value "<value>" --type SecureString`,
            `Or use the SST console to set secrets for the "${stage}" stage.`,
          ],
        },
        startTime
      )
      outputResult(result, args)

      if (!args.json) {
        process.stdout.write(`  Secret "${secretName}" for stage "${stage}" must be set via AWS SSM/Secrets Manager.\n`)
        process.stdout.write(`  Run: aws ssm put-parameter --name "/${stage}/${secretName}" --value "<value>" --type SecureString\n`)
      }
    }
  },
})

const auditCommand = defineCommand({
  meta: {
    name: 'audit',
    description: 'Audit all secrets across all stages — health report',
  },
  args: {
    json: {
      type: 'boolean',
      description: 'Output as JSON CommandResult',
      default: false,
    },
    verbose: {
      type: 'boolean',
      description: 'Show detailed output',
      default: false,
    },
  },
  run({ args }) {
    const startTime = Date.now()
    const root = resolveRoot()
    const schema = loadSchema(root)

    if (!schema) {
      const result = failure(
        'secrets audit',
        CLI_ERROR_CODES.SECRETS_NOT_FOUND,
        'Could not load secrets schema.',
        startTime,
        'Ensure the secrets schema exists.'
      )
      outputResult(result, args)
      process.exitCode = 1
      return
    }

    const audit: SecretsAuditResult = { stages: {} }

    for (const stage of VALID_STAGES) {
      const requiredNames = getRequiredForStage(schema, stage)
      const secrets: SecretStatus[] = requiredNames.map((name) => {
        const def = schema[name]
        return {
          name,
          required: true,
          stages: def.stages,
          format: def.format,
          group: def.group,
          kind: def.kind,
          status: isSecretSet(name) ? ('set' as const) : ('missing' as const),
        }
      })

      const setCount = secrets.filter((s) => s.status === 'set').length
      const missingCount = secrets.filter((s) => s.status === 'missing').length

      audit.stages[stage] = {
        total: secrets.length,
        set: setCount,
        missing: missingCount,
        secrets,
      }
    }

    const result = success('secrets audit', audit, startTime)
    outputResult(result, args)

    if (!args.json) {
      for (const [stage, info] of Object.entries(audit.stages)) {
        const icon = info.missing === 0 ? 'OK' : 'WARN'
        process.stdout.write(`  [${icon}] ${stage}: ${info.set}/${info.total} set, ${info.missing} missing\n`)
        if (args.verbose && info.missing > 0) {
          for (const s of info.secrets.filter((sec) => sec.status === 'missing')) {
            process.stdout.write(`       - ${s.name} (${s.format})\n`)
          }
        }
      }
    }
  },
})

// ── Parent command ───────────────────────────────────────────────────

export const secretsCommand = defineCommand({
  meta: {
    name: 'secrets',
    description: 'Secrets management commands',
  },
  subCommands: {
    list: listCommand,
    required: requiredCommand,
    get: getCommand,
    set: setCommand,
    audit: auditCommand,
  },
})
