name: Setup Node & pnpm
description: Shared setup for Node.js and pnpm with frozen lockfile install. Reads pinned Node version from .nvmrc and pnpm version from packageManager field.

inputs:
  node-version:
    description: 'Node.js version override. Leave empty to read from .nvmrc (recommended).'
    required: false
    default: ''
  registry-url:
    description: npm registry URL (for publish steps)
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4

    - name: Setup Node.js (from .nvmrc)
      if: ${{ inputs.node-version == '' }}
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: pnpm
        registry-url: ${{ inputs.registry-url }}

    - name: Setup Node.js (explicit version)
      if: ${{ inputs.node-version != '' }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: ${{ inputs.registry-url }}

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Cache Turbo build artifacts
      uses: actions/cache@v4
      with:
        path: .turbo
        key: turbo-${{ runner.os }}-${{ hashFiles('.nvmrc') }}-${{ hashFiles('pnpm-lock.yaml', 'turbo.json') }}
        restore-keys: |
          turbo-${{ runner.os }}-${{ hashFiles('.nvmrc') }}-
          turbo-${{ runner.os }}-
