name: Quality Gates
description: Run lint, typecheck, env validation, and readiness drift guard

runs:
  using: composite
  steps:
    - name: Lint
      shell: bash
      run: pnpm lint

    - name: Typecheck
      shell: bash
      run: pnpm typecheck

    - name: Env schema validation
      shell: bash
      run: pnpm validate:env

    - name: Readiness drift guard
      shell: bash
      run: pnpm check:readiness
