#!/usr/bin/env node
/**
 * Fleet Sync PR Generator — RN-024
 *
 * Reads a fleet drift report and generates sync PR content for downstream repos.
 * Works with GitHub CLI (gh) for PR creation.
 *
 * Usage:
 *   pnpm fleet:sync -- --report=fleet-drift-report.json    # from existing report
 *   pnpm fleet:sync -- --target=/path/to/repo               # detect + sync
 *   pnpm fleet:sync -- --dry-run                             # preview PR content
 *   pnpm fleet:sync -- --json                                # JSON output
 *
 * Exit codes:
 *   0 — sync completed (or dry-run preview)
 *   1 — error during sync
 *
 * Zero external dependencies — uses only Node.js built-ins.
 */
import { readFileSync, writeFileSync, existsSync, copyFileSync, mkdirSync } from 'node:fs'
import { resolve, join, dirname } from 'node:path'
import { execFileSync } from 'node:child_process'

const ROOT = resolve(import.meta.dirname, '..')
const POLICY_PATH = resolve(ROOT, 'docs/fleet-policy.json')

// ── Parse flags ──────────────────────────────────────────────────────
const args = process.argv.slice(2)
const jsonMode = args.includes('--json')
const dryRun = args.includes('--dry-run')
const reportArg = args.find((a) => a.startsWith('--report='))
const targetArg = args.find((a) => a.startsWith('--target='))

// ── Load fleet policy ────────────────────────────────────────────────
let policy
try {
  policy = JSON.parse(readFileSync(POLICY_PATH, 'utf-8'))
} catch {
  console.error('Error: docs/fleet-policy.json not found or invalid')
  process.exit(1)
}

// ── Load or generate drift report ────────────────────────────────────
let report
if (reportArg) {
  const reportPath = resolve(reportArg.split('=')[1])
  try {
    report = JSON.parse(readFileSync(reportPath, 'utf-8'))
  } catch {
    console.error(`Error: could not read drift report at ${reportPath}`)
    process.exit(1)
  }
} else if (targetArg) {
  const targetPath = resolve(targetArg.split('=')[1])
  try {
    const output = execFileSync('node', [
      resolve(ROOT, 'scripts/check-fleet-drift.mjs'),
      `--target=${targetPath}`,
      '--json',
    ], { encoding: 'utf-8', cwd: ROOT })
    report = JSON.parse(output)
  } catch (err) {
    // Drift detection exits 1 on drift found, but still produces valid JSON
    try {
      report = JSON.parse(err.stdout)
    } catch {
      console.error('Error: could not generate drift report')
      process.exit(1)
    }
  }
} else {
  console.error('Usage: fleet-sync --report=<path> or --target=<path>')
  console.error('  --report=path   Use an existing drift report JSON file')
  console.error('  --target=path   Run drift detection against a target repo')
  console.error('  --dry-run       Preview sync actions without making changes')
  console.error('  --json          Output sync plan as JSON')
  process.exit(1)
}

// ── Build sync plan ──────────────────────────────────────────────────
const syncPlan = {
  schema: 'ripple-fleet-sync/v1',
  timestamp: new Date().toISOString(),
  dryRun,
  targetPath: report.targetPath,
  complianceScore: report.complianceScore,
  actions: [],
  prBody: ''
}

const driftedFindings = report.findings.filter(
  (f) => f.status === 'drifted' || f.status === 'missing'
)

for (const finding of driftedFindings) {
  const surface = policy.governedSurfaces.find((s) => s.id === finding.surfaceId)
  if (!surface) continue

  const action = {
    surfaceId: finding.surfaceId,
    name: finding.name,
    severity: finding.severity,
    strategy: surface.strategy,
    label: policy.syncPolicy[finding.severity]?.label ?? 'fleet:advisory',
    files: [],
    status: 'pending'
  }

  for (const p of surface.paths) {
    const sourcePath = join(ROOT, p)
    if (!existsSync(sourcePath)) continue

    if (surface.strategy === 'sync') {
      action.files.push({
        path: p,
        action: finding.status === 'missing' ? 'create' : 'overwrite',
        source: sourcePath
      })
    } else if (surface.strategy === 'merge') {
      action.files.push({
        path: p,
        action: 'merge',
        source: sourcePath,
        note: 'Manual review required for merge strategy files'
      })
    }
  }

  syncPlan.actions.push(action)
}

// ── Generate PR body ─────────────────────────────────────────────────
const securityActions = syncPlan.actions.filter((a) => a.severity === 'security-critical')
const standardsActions = syncPlan.actions.filter((a) => a.severity === 'standards-required')
const advisoryActions = syncPlan.actions.filter((a) => a.severity === 'recommended')

let prBody = '## Fleet Sync — Golden Path Update\n\n'
prBody += 'This PR was generated by the Ripple Next fleet governance system (RN-024).\n'
prBody += `Compliance score before sync: **${report.complianceScore}%**\n\n`

if (securityActions.length > 0) {
  prBody += '### Security-Critical Updates\n\n'
  prBody += '> These changes address security drift and should be reviewed and merged promptly (SLA: 7 days).\n\n'
  for (const action of securityActions) {
    prBody += `- **${action.name}** (${action.surfaceId})\n`
    for (const file of action.files) {
      prBody += `  - \`${file.path}\` — ${file.action}\n`
    }
  }
  prBody += '\n'
}

if (standardsActions.length > 0) {
  prBody += '### Standards Updates\n\n'
  prBody += '> These changes maintain consistency with the golden-path standards (SLA: 30 days).\n\n'
  for (const action of standardsActions) {
    prBody += `- **${action.name}** (${action.surfaceId})\n`
    for (const file of action.files) {
      prBody += `  - \`${file.path}\` — ${file.action}\n`
    }
  }
  prBody += '\n'
}

if (advisoryActions.length > 0) {
  prBody += '### Advisory (Report Only)\n\n'
  for (const action of advisoryActions) {
    prBody += `- **${action.name}** (${action.surfaceId}) — review recommended\n`
  }
  prBody += '\n'
}

prBody += '---\n\n'
prBody += '**References:**\n'
prBody += '- [Fleet Policy](docs/fleet-policy.json)\n'
prBody += '- [ADR-019: Fleet Governance](docs/adr/019-fleet-governance.md)\n'
prBody += '- [Error Taxonomy — FLEET codes](docs/error-taxonomy.json)\n'

syncPlan.prBody = prBody

// ── Apply sync (or dry-run) ──────────────────────────────────────────
if (!dryRun && targetArg) {
  const targetPath = resolve(targetArg.split('=')[1])
  for (const action of syncPlan.actions) {
    if (action.strategy === 'advisory') {
      action.status = 'skipped'
      continue
    }
    for (const file of action.files) {
      if (file.action === 'create' || file.action === 'overwrite') {
        const destPath = join(targetPath, file.path)
        mkdirSync(dirname(destPath), { recursive: true })
        copyFileSync(file.source, destPath)
        action.status = 'applied'
      } else if (file.action === 'merge') {
        action.status = 'requires-review'
      }
    }
  }


  // ── Update .fleet.json in target repo ──────────────────────────────
  const fleetJsonPath = join(targetPath, '.fleet.json')
  let fleetJson = {}
  if (existsSync(fleetJsonPath)) {
    try {
      fleetJson = JSON.parse(readFileSync(fleetJsonPath, 'utf-8'))
    } catch {
      // If .fleet.json is invalid, start fresh
      fleetJson = {}
    }
  }

  const currentSha = execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf-8', cwd: ROOT }).trim()
  fleetJson.goldenPathVersion = currentSha
  fleetJson.lastSyncedAt = new Date().toISOString()
  fleetJson.fleetPolicyVersion = policy.version ?? policy.fleetPolicyVersion ?? '1.2.0'

  writeFileSync(fleetJsonPath, JSON.stringify(fleetJson, null, 2) + '\n', 'utf-8')
}

// ── Output ───────────────────────────────────────────────────────────
if (jsonMode) {
  process.stdout.write(JSON.stringify(syncPlan, null, 2) + '\n')
} else {
  console.error('')
  console.error('Fleet Sync Plan — RN-024')
  console.error('\u2500'.repeat(40))
  console.error('')

  if (dryRun) {
    console.error('[DRY RUN] No files will be modified.\n')
  }

  if (syncPlan.actions.length === 0) {
    console.error('  No drift to sync — target is fully compliant.')
  } else {
    for (const action of syncPlan.actions) {
      const icon = action.status === 'applied' ? '\u2713' :
                   action.status === 'requires-review' ? '\u26A0' : '\u2022'
      console.error(`  ${icon} [${action.surfaceId}] ${action.name} (${action.severity})`)
      for (const file of action.files) {
        console.error(`      ${file.action}: ${file.path}`)
      }
    }
  }

  console.error('')
  console.error('\u2500'.repeat(40))
  console.error(`Total actions: ${syncPlan.actions.length}`)

  if (dryRun) {
    console.error('\nPR body preview:')
    console.error(syncPlan.prBody)
  }

  console.error('')
}
